language: node_js

node_js:
   - "10.4.0"

services:
  - postgresql

before-script:
    - npm install
    - psql -c 'create database travis_ci_test;' -U postgres

script: npm run test
after_success: npm run coverage